<center><img src="redpopcorn.jpg"></center>

**Netflix**! What started in 1997 as a DVD rental service has since exploded into one of the largest entertainment and media companies.

Given the large number of movies and series available on the platform, it is a perfect opportunity to flex your exploratory data analysis skills and dive into the entertainment industry.

You work for a production company that specializes in nostalgic styles. You want to do some research on movies released in the 1990's. You'll delve into Netflix data and perform exploratory data analysis to better understand this awesome movie decade!

You have been supplied with the dataset `netflix_data.csv`, along with the following table detailing the column names and descriptions. Feel free to experiment further after submitting!

## The data
### **netflix_data.csv**
| Column | Description |
|--------|-------------|
| `show_id` | The ID of the show |
| `type` | Type of show |
| `title` | Title of the show |
| `director` | Director of the show |
| `cast` | Cast of the show |
| `country` | Country of origin |
| `date_added` | Date added to Netflix |
| `release_year` | Year of Netflix release |
| `duration` | Duration of the show in minutes |
| `description` | Description of the show |
| `genre` | Show genre |

In [104]:
# Importing pandas and matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# Read in the Netflix CSV as a DataFrame
netflix_df = pd.read_csv("netflix_data.csv")

Validate the type of information in the dataframe

In [105]:
# Start coding here! Use as many cells as you like

netflix_df.head(20)

   show_id  ...               genre
0       s2  ...              Dramas
1       s3  ...       Horror Movies
2       s4  ...              Action
3       s5  ...              Dramas
4       s6  ...    International TV
5       s7  ...       Horror Movies
6       s8  ...              Dramas
7       s9  ...       Horror Movies
8      s10  ...       Horror Movies
9      s11  ...              Dramas
10     s14  ...       Documentaries
11     s15  ...  Independent Movies
12     s16  ...              Dramas
13     s18  ...              Dramas
14     s19  ...            Comedies
15     s21  ...              Dramas
16     s22  ...              Action
17     s23  ...              Dramas
18     s24  ...              Dramas
19     s28  ...       Horror Movies

[20 rows x 11 columns]

Let's look for only the movies that were released during 1990s

In [106]:
netflix_df_1990s = netflix_df[(netflix_df['release_year']>=1990) & (netflix_df['release_year']<=1999)]

# For knowing the number of columns and rows
print(netflix_df_1990s.shape)

netflix_df_1990s.head()

(184, 11)

    show_id   type  ...                                        description     genre
6        s8  Movie  ...  After one of his high school students attacks ...    Dramas
118    s167  Movie  ...  At the center of this engrossing melodrama is ...    Dramas
145    s211  Movie  ...  After a run-in with Richard Grieco, dimwits Do...  Comedies
167    s239  Movie  ...  When a philandering club promoter sets out to ...  Comedies
194    s274  Movie  ...  Raised by a kindly thief, orphaned Jimmy goes ...    Dramas

[5 rows x 11 columns]

Now that I have a dataframe with all the movies from 1990 to 1999, let's consider the duration of all the movies.

In [107]:
# Create a sub dataframe with only the movie durations.
durations_df = netflix_df_1990s[['duration']].reset_index(drop=True)
durations_df.shape

(184, 1)

Calulate the most frequent movie duration in the 1990s.

In [108]:
duration_mode = durations_df.mode()
duration = int(duration_mode.iloc[0,0])
# type(int(duration))
duration

94

I can conclude that the most common duration is 94, as it is the most repeated duration.

Now, let's study when an action movie is considered short. For this part, I know that short short movies have a duration less than 90 minutes, and I consider only 'action' movies.

In [109]:
# Short action movies from the 1900s
short_movies_action_df = netflix_df_1990s[(netflix_df_1990s['duration'] < 90) & (netflix_df_1990s['genre'] =='Action')]
short_movies_action_df

     show_id   type  ...                                        description   genre
1288   s2039  Movie  ...  Fifteen years after the Second Impact, apathet...  Action
1698   s2708  Movie  ...  A pugilist from Shantung struggles to rise to ...  Action
2328   s3718  Movie  ...  An officer killed on the job returns to Earth ...  Action
2993   s4787  Movie  ...  Air marshal John Cutter must stop notorious te...  Action
3297   s5299  Movie  ...  During a visit to the Bronx to help out at his...  Action
3806   s6114  Movie  ...  While working at a family friend's business, a...  Action
3943   s6330  Movie  ...  Seele orders an all-out attack on NERV, aiming...  Action

[7 rows x 11 columns]

Counting the number of rows gives us the number of movies that I am looking for.

In [110]:
short_movie_count = short_movies_action_df.shape[0]
print(short_movie_count)

7

In this Netflix catalogue, there are only 7 Action movies with a duration less than 90 minutes, realeased during 1990s.